### ISSUE TITLE
Add support for Python Improved scope

### ISSUE THREAD

**Issue by mrvkino** [braver/Solarized#53]
Hi,

could it be possible to add Python Improved scopes in Solarized. [Here](https://github.com/MattDMo/PythonImproved#newchanged-scopes) is the list of scopes for Solarized Improved.

**Comment by braver** [comment]
@mrvkino I'm definitely open to expanding support for specific languages. However, the color scheme has been set up to work without requiring much language specific work. So rather than hunting a scope list for cases that may not be covered, I would rather work from specific cases that need to be tweaked. 

Do you have anything specific you would like to see changed, or do you have an example file showing areas that need improvement?

**Comment by mrvkino** [comment]
Fair enough, I do not have anything right now. I will go through the different scope and highlight the ones I need or do a pull request with the scopes and my color suggestion.

**Comment by braver** [comment]
Closing this but will consider specific request, issues and pr's for improved language support.
