### ISSUE TITLE
Selected color light version 3152

### ISSUE THREAD

**Issue by TheShrike** [braver/Solarized#67]
In the last builds, the selected text color no longer shows invisible characters such as spaces and tabs, the dark version is ok
https://forum.sublimetext.com/t/dev-build-3148/32456

**Comment by braver** [comment]
Thanks for letting me know. I tend to run the dev builds, so although I don't use Solarized all the time I'll keep an eye out for how this develops over the next few dev builds and see if the color scheme needs adjusting. I intend to move over to the new syntax soon too, because it'll make maintaining the two variations so much more easy.
