### ISSUE TITLE
Use italics for comments

### ISSUE THREAD

**Issue by matijs** [braver/Solarized#69]
Would using italics for comments be something you're willing to add to the theme? Feel free to merge the #68 PR

**Comment by braver** [comment]
At some point I removed all italics because a lot of programming fonts don't actually have italics. The renderer tries to recreate them by slanting the characters, which looks shitty. Also, even when fonts do have italics it's not always super readable either. 

So I understand some people like the italics, in comments or elsewhere (I like em too!), but if you want them in this color scheme I think I'm going to go with that you just have to fork an tweak it.

**Comment by matijs** [comment]
Fair enough. And agreed that faux italics look like crap :)

I'll close the PR.
