### ISSUE TITLE
Yaml Keys are "String" Colored

### ISSUE THREAD

**Issue by TaysirTayyab** [braver/Solarized#90]
When using this theme with ST 4143, all the keys of the yaml file are string colored.

![Screenshot 2023-02-08 at 11 30 05 AM](https://user-images.githubusercontent.com/13357655/217606882-8bda8a47-f4b6-47a8-ab46-f91ab25608ea.png)

There seems to be a missing definition in the color scheme. I can fix this issue by customizing the color scheme (Settings -> Customize Color Scheme) and adding the following rule.

```
"rules":
  [
    {
      "name": "Mapping Key Names",
      "scope": "meta.mapping.key string",
      "foreground": "var(blue)"
    }
  ]
```

This causes the YAML files to be colored correctly (I think).

**Comment by braver** [comment]
I would say it's currently correct and consistent with most other color schemes (at least all default included color schemes have the keys simply in the "string color"), but if you want keys in YAML or JSON to have a different color then it's perfectly fine to extend a color scheme as you've done. That's why that functionality is there.
